# Checks that the HelloWorld nevers breaks, like True Metal

name: Hello World CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testTrueMetal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: ['temurin', 'sapmachine']
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Test with Maven
      run: mvn test

    - name: Build Docker image
      run: docker build -t my-java-app .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name my-java-app-container my-java-app

    - name: Wait for the service to be available
      run: sleep 10

    - name: Test the service
      run: |
        curl -s http://localhost:8080 | grep "Hello World!"

    - name: Stop and remove Docker container
      run: docker stop my-java-app-container && docker rm my-java-app-container

    - name: Clean up Docker
      run: docker rmi my-java-app